export const seedProducts = [
  {
    name: 'Oversized Linen Shirt — Natural',
    slug: 'oversized-linen-shirt-natural',
    shortDescription: 'Relaxed-fit linen shirt in undyed natural — breathable, sustainable, and timeless.',
    description: 'Our signature oversized linen shirt is cut for effortless, relaxed wear. Made from undyed Belgian linen, it gets better with age and washing. The dropped shoulders and loose silhouette make it perfect layered over trousers or tucked into a skirt. Unisex sizing.',
    price: 95.00,
    images: ['/images/shirt.jpg'],
    category: 'Apparel',
    subcategory: 'Tops',
    variants: [
      { id: 'a1', type: 'size', label: 'S',  value: 'S',  stock: 14 },
      { id: 'a2', type: 'size', label: 'M',  value: 'M',  stock: 20 },
    ],
    stock: 68,
    rating: 4.8,
    reviewCount: 32,
    tags: ['linen', 'shirt', 'sustainable', 'unisex'],
    featured: true,
    newArrival: false,
  },
  {
    name: 'Pebbled Leather Mini Tote',
    slug: 'pebbled-leather-mini-tote',
    shortDescription: 'Structured pebbled leather mini tote with top handles and detachable crossbody strap.',
    description: 'Our mini tote is crafted from full-grain pebbled leather with a refined structured silhouette. Interior features a zip pocket and two slip pockets. Comes with both short top handles and a long adjustable crossbody strap. Fits a tablet, wallet, and all your essentials.',
    price: 185.00,
    images: ['/images/bag.jpg'],
    category: 'Accessories',
    subcategory: 'Bags',
    variants: [],
    stock: 25,
    rating: 4.8,
    reviewCount: 31,
    tags: ['leather', 'bag', 'tote', 'accessories'],
    featured: true,
    newArrival: false,
  },
  {
    name: 'Terracotta Pillar Candle Set',
    slug: 'terracotta-pillar-candle-set',
    shortDescription: 'Three hand-poured soy wax candles in warm terracotta tones with subtle amber fragrance.',
    description: 'Elevate your home with our hand-poured terracotta pillar candle set. Made from 100% natural soy wax, each candle burns cleanly for up to 40 hours. The warm amber and sandalwood fragrance creates a cozy, inviting atmosphere. Set of 3 in varying heights — perfect for a styled arrangement on a mantle or dining table.',
    price: 38.00,
    compareAtPrice: 52.00,
    images: ['/images/candle.jpg'],
    category: 'Home & Living',
    subcategory: 'Candles',
    variants: [],
    stock: 42,
    rating: 4.8,
    reviewCount: 23,
    tags: ['candle', 'soy', 'terracotta', 'home decor'],
    featured: true,
    newArrival: false,
  },
  {
    name: 'Wide-Leg Linen Trousers',
    slug: 'wide-leg-linen-trousers',
    shortDescription: 'Effortlessly chic wide-leg trousers in breathable linen — summer essential.',
    description: 'Our wide-leg linen trousers strike the perfect balance between relaxed and refined. Cut from 100% linen with an elasticated waist for all-day comfort. The relaxed leg drapes beautifully and can be styled up or down. Available in Sand, Black, and Terracotta.',
    price: 115.00,
    images: ['/images/pants.jpg'],
    category: 'Apparel',
    subcategory: 'Bottoms',
    variants: [],
    stock: 45,
    rating: 4.7,
    reviewCount: 19,
    tags: ['linen', 'trousers', 'wide-leg', 'summer'],
    featured: false,
    newArrival: true,
  },
  {
    name: 'Raffia Sun Hat',
    slug: 'raffia-sun-hat',
    shortDescription: 'Wide-brim raffia sun hat with adjustable inner drawstring — your summer essential.',
    description: 'Handwoven from natural raffia, this wide-brim hat provides generous sun protection while looking effortlessly stylish. The adjustable inner drawstring ensures a secure fit. The supple brim can be shaped and folded for travel. One size fits most.',
    price: 58.00,
    images: ['/images/hat.jpg'],
    category: 'Accessories',
    subcategory: 'Hats',
    variants: [],
    stock: 32,
    rating: 4.6,
    reviewCount: 28,
    tags: ['raffia', 'hat', 'summer', 'accessories'],
    featured: false,
    newArrival: true,
  }
]
